# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    working_directory: /go/src/github.com/Code-Hex/go-async
    steps:
      - checkout
      - run:
          name: Coverage
          command: |
            go test -v -covermode=atomic -coverpkg=./... -coverprofile=coverage.txt ./...
      - run:
          name: Upload coverages to codecov
          command: |
            bash <(curl -s https://codecov.io/bash)